
sudo: required

services:
    - docker

language: c
compiler:
    - gcc

before_install:
    - build/update_env.sh

install: 
    - bash build/prepare_env.sh

script: 
    - echo "compiling doip-dissector"
    - bash build/plugin.sh

    - echo "preparing unit tests"
    - build/cunit_install.sh
    - echo "compiling tests"
    - make -C ./src/test/
    - echo "executing tests"
    - ./src/test/doip-test

after_success:
    # create docker image
    - bash build/prepare_docker.sh
    - docker build -t jufuch/amos-ss16-proj3 ./docker
    # upload image to wireshark
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" -e="$DOCKER_EMAIL"
    - docker push jufuch/amos-ss16-proj3:latest
    - docker logout
    - bash deploy/deploytrigger.sh





