version: '0.0.1-{build}'

clone_folder: c:\projects\ws-plugin

#environment:
#  var: value

# script after cloning repo:
install:
  - echo Install Script now!

platform:
  - x64
  
before_build:
  - echo before_build Script now!
  - mkdir c:\projects\wireshark
  - git clone https://github.com/wireshark/wireshark.git c:\projects\wireshark
  - dir c:\projects\wireshark
  - echo nach dir
  - cmd: set CYGWIN=nodosfilewarning
  - echo nach set cygwin
  - cmd: set WIRESHARK_BASE_DIR=c:\projects\wireshark
  - cmd: set WIRESHARK_TARGET_PLATFORM=win64
  - cmd: set QT5_BASE_DIR=c:\Qt\5.6\msvc2013_64
  - cmd: set WIRESHARK_VERSION_EXTRA=-YourExtraVersionInfo
  - echo xcopy now
  - cmd: xcopy /E c:\projects\ws-plugin\src\plugins c:\projects\wireshark\plugins
  - echo nach xcopy
  - ps: Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile c:\projects\cygwin-setup.exe
  - mkdir c:\projects\cyg-packages
  - c:\projects\cygwin-setup.exe -q -n -N -d -R C:\cygwin64 -s http://ftp.hawo.stw.uni-erlangen.de/cygwin/ -l c:\projects\cyg-packages -P  flex

build_script:
  - echo Build Script now!
  - cd  c:\projects\wireshark
  - cmake -DENABLE_CHM_GUIDES=on -G "Visual Studio 12 Win64" c:\projects\wireshark
  - dir
  - msbuild /m /p:Configuration=RelWithDebInfo Wireshark.sln
  - dir
  - dir plugins\doip

after_build:
  - 7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\

artifacts:
  - path: myapp.zip
    name: MyApp
    
build_failure:
  - 7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\
  - appveyor PushArtifact mzapp.zip
